[package]
name = "boa_fapi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Boa File API bindings (Blob, File, FileList)"

[lints]
workspace = true

[dependencies]
boa_engine = { workspace = true }
boa_gc = { workspace = true }
boa_fapi_core = { path = "../boa_fapi_core", version = "0.1.0" }
bytes = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["streams-shim"]
streams-shim = []

[dev-dependencies]
proptest = { workspace = true }
