[package]
name = "boa_fapi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Boa File API bindings (Blob, File, FileList)"

[lints]
workspace = true

[dependencies]
boa_engine = { workspace = true }
boa_gc = { workspace = true }
boa_fapi_core = { path = "../boa_fapi_core", version = "0.1.0" }
boa_fapi_fs = { path = "../boa_fapi_fs", version = "0.1.0", optional = true }
bytes = { workspace = true }
thiserror = { workspace = true }
encoding_rs = { workspace = true }
base64 = { workspace = true }
getrandom = { workspace = true }

[features]
default = ["streams-shim", "dom-shim", "fs", "url-shim", "structured-clone"]
streams-shim = []
dom-shim = []
fs = ["dep:boa_fapi_fs"]
url-shim = []
structured-clone = []

[dev-dependencies]
proptest = { workspace = true }
